//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea02.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ncapasTarea2Entities : DbContext
    {
        public ncapasTarea2Entities()
            : base("name=ncapasTarea2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acceso_premier> acceso_premier { get; set; }
        public virtual DbSet<pelicula> peliculas { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<rol> rols { get; set; }
    }
}
