//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pelicula()
        {
            this.acceso_premier = new HashSet<acceso_premier>();
        }
    
        public int id { get; set; }
        public string nombre_pelicula { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan duracion { get; set; }
        public string category { get; set; }
        public string estudio { get; set; }
        public string director { get; set; }
        public string genero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<acceso_premier> acceso_premier { get; set; }
    }
}
